# .github/workflows/build.yml

# Workflow name
name: 'Extension'

# Event for the workflow
on: push

# List of jobs
jobs:
  build-chrome-extension:
    # Operating System
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn
        # 👇 Adds Chromatic as a step in the workflow
      - name: Build sources
        run: yarn run build
      - name: Build extension for chrome
        run: yarn run pack
      - name: Archive extension artifacts
        uses: actions/upload-artifact@v3
        with:
          name: chrome.zip
          path: web-ext-artifacts/*.zip
          if-no-files-found: error
